postgres:
  image: postgres:9.6
  environment:
    POSTGRES_USER:     improvcoaches
    POSTGRES_PASSWORD: improvcoaches
  ports:
    - '5432:5432'
  volumes:
    - improvcoaches-postgres:/var/lib/postgresql/data

redis:
  image: redis:2.8.21
  ports:
    - '6379:6379'
  volumes:
    - improvcoaches-redis:/var/lib/redis/data

web:
  image: improvcoaches
  tty: true
  stdin_open: true
  environment:
    REDISTOGO_URL: 'redis://redis:6379'
  links:
    - postgres
    - redis
  volumes:
    - .:/improvcoaches
  ports:
    - '3000:3000'